---
title: "R Notebook"
output: html_notebook
---

```{r}
library("rethinking")
```

######## case 2
```{r}
N <- 500
# simulate family incomes for each individual
family_income <- runif(N)
# assign a unique coefficient for each type of event
b <- c(-2,0,2)
career <- rep(NA,N) # empty vector of choices for each individual
for ( i in 1:N ) {
  score <- 0.5*(1:3) + b*family_income[i]
  p <- softmax(score[1],score[2],score[3])
  career[i] <- sample( 1:3 , size=1 , prob=p )
}
```

```{r}
code_m11.14 <- "
data{
  int N; // number of observations
  int K; // number of outcome values
  int career[N]; // outcome
  real family_income[N];
}

```







######### case 1
```{r}
# simulate career choices among 500 individuals
N <- 500 # number of individuals
income <- c(1,2,5) # expected income of each career
score <- 0.5*income # scores for each career, based on income
# next line converts scores to probabilities
p <- softmax(score[1],score[2],score[3])
# now simulate choice
# outcome career holds event type values, not counts
career <- rep(NA,N) # empty vector of choices for each individual
# sample chosen career for each individual
set.seed(34302)
for ( i in 1:N ) career[i] <- sample( 1:3 , size=1 , prob=p )
```

```{r}
code_m11.13 <- "
data{
  int N; // number of individuals
  int K; // number of possible careers
  int career[N]; // outcome
  vector[K] career_income;
}
parameters{
  vector[K-1] a; // intercepts
  real<lower=0> b; // association of income with choice
}
model{
  vector[K] p;
  vector[K] s;
  a ~ normal( 0 , 1 );
  b ~ normal( 0 , 0.5 );
  s[1] = a[1] + b*career_income[1];
  s[2] = a[2] + b*career_income[2];
  s[3] = 0; // pivot
  p = softmax( s );
  career ~ categorical( p );
}"
```

```{r}
dat_list <- list( N=N , K=3 , career=career , career_income=income ) 
library("rstan")
model <- stan_model(model_code=code_m11.13)
model
m11.13 <- sampling( model , data=dat_list , chains=4, iter=4000 )
precis( m11.13 , 2 )
```

```{r}
post <- extract.samples( m11.13 )
post

s1 <- with( post , a[,1] + b*income[1] )
s2_orig <- with( post , a[,2] + b*income[2] )
s2_new <- with( post , a[,2] + b*income[2]*3 )

p_orig <- sapply( 1:length(post$b), function(i)
  softmax( c(s1[i],s2_orig[i],0) ) )

p_new <- sapply( 1:length(post$b) , function(i)
  softmax( c(s1[i],s2_new[i],0) ) )

boxplot(p_orig[2,], p_new[2,])
boxplot(p_orig[1,], p_orig[2,], p_orig[3,])
boxplot(p_new[1,], p_new[2,], p_new[3,])

```

