---
title: "categorical regression"
output: html_notebook
---

Три рассы. Русские китайцы и индусы
Параметры: рост, цвет (коричневость)

```{r}
N <- 300
rassa <- c(rep(0, N/3),rep(1, N/3),rep(2, N/3))
height <- rep(0, N)
browny <- rep(0, N)

for(r in 1:length(rassa)){
  height[r] <- rnorm(1, switch(1+rassa[r], 180, 159, 160), 20)
  browny[r] <- rnorm(1, switch(1+rassa[r], 10, 100, 255), 100)
}

browny[browny < 0] <- 0

browny <- scale(browny)
height <- scale(height)
hist(browny)
```
```{r}


```

```{r}
library("rstan")
model <- stan_model("categorical.stan")
```

```{r}
fit <- sampling(model, data <- list(N=N, D = 2, K = 3, rassa = 1+rassa, x = data.frame(height, browny)), chains = 1, iter = 2000,cores = getOption("mc.cores", 1L))

```

```{r}
x = data.frame(height, browny)
colMeans(x[rassa==0,])

colMeans(x[rassa==1,])

colMeans(x[rassa==2,])

```


```{r}
softmax(0.94*0.6+0.7*2.44,-0.14*0.6+0.7*1.86,0)

softmax(-0.94*0.27+0.25*2.44,0.14*0.27+0.25*1.86,0)

softmax(-0.94*0.32-0.96*2.44,0.14*0.32-0.96*1.86,0)

```

```{r}
fit
```


```{r}
library(bayesplot)
mcmc_trace(fit)
fit
```


```{r}
softmax(0.1,1,0)
softmax(0.1+1,1+1,0+1)

```

