---
title: "create log-normal"
output:
  pdf_document: default
  html_notebook: default
---
by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Ctrl+Shift+Enter*. 

```{r}
N <- 1000
tics <- 1000

val <- rep(50, N)
for(i in 1:tics){
  for(n in 1:N){
    k <- rnorm(1, 1, 0.01)
    d <- rnorm(1, 1, 0.01)
    delta <- val[n]*k - val[n]*d
    val[n] <- val[n] + delta
  }
}

head(val)
```



```{r}
hist(val,breaks=50)
hist(log10(val),breaks=50)


```
```{r}

qqnorm(val, pch = 1, frame = FALSE)
qqline(val, col = "steelblue", lwd = 2)


logval <- log10(val)
qqnorm(logval, pch = 1, frame = FALSE)
qqline(logval, col = "steelblue", lwd = 2)
```

```{r}
N <- 1000
tics <- 1000

val <- rep(50, N)
for(i in 1:tics){
  for(n in 1:N){
    k <- rnorm(1, 1, 0.01)
    d <- rnorm(1, 1, 0.01)
    delta <- k - val[n]*d
    val[n] <- val[n] + delta
  }
}

head(val)
```


```{r}
hist(val,breaks=50)
hist(log10(val),breaks=50)


```
```{r}

qqnorm(val, pch = 1, frame = FALSE)
qqline(val, col = "steelblue", lwd = 2)


logval <- log10(val)
qqnorm(logval, pch = 1, frame = FALSE)
qqline(logval, col = "steelblue", lwd = 2)
```


```{r}
qu <- log(rnorm(1000, 10, 1))
qqnorm(qu, pch = 1, frame = FALSE)
qqline(qu, col = "steelblue", lwd = 2)
```



