---
title: "R Notebook"
output: html_notebook
---

## generate
```{r}
N <- 500
hired <- rep(0, N)
sex <- c(rep(0, N/2),rep(1, N/2))
looks_good <- rnorm(N, 0, 2)

for(h in 1:length(hired)){
  hired_prob <- ifelse(sex[h]==1, 0.6, 0.4)
  hired[h] <- rbinom(1, 1, hired_prob)
  if(hired[h]==0 && sex[h] == 0 && looks_good[h] > 2){
      hired[h] <- 1
  }
}

df <- data.frame(hired, sex, looks_good)

```


# classics

## look clasics

```{r}
model <- lm(hired ~ sex *looks_good, data=df, family = "binomial")
summary(model)

```



# model: logit(p) = a+bx
```{r}
inv_logit = function(x) { exp(x)/(1+exp(x)) }
inv_logit(0.5)
inv_logit(0.5+0.11)

```


## look stan
```{r}
library(rstan)
model <- stan_model('logistic.stan')
model_abc <- stan_model('logistic_abc_multi_thresh.stan')
#cat("CXX14FLAGS += -mtune=native -march=native -Wno-ignored-attributes -Wno-deprecated-declarations", file = "~/.R/Makevars.win")

```

```{r}
fit <- sampling(model_abc, data=list(N=N, hired=hired, sex=sex, looks_good=looks_good), cores = 4, chains = 1, iter = 1000)
fit
```

```{r}
# man
inv_logit(-0.02+0.46)

#pretty_wom
inv_logit(-0.02+0.23)

#wom
inv_logit(-0.02)

```


```{r}
trace <- traceplot(fit, pars = c("a"))
trace + theme(legend.position = "top")
```


```{r}
posterior <- extract(fit, permuted = TRUE)
plot(density(posterior[["c"]]))
abline(v=0, col = "blue")
```




